name: main

on: 
  push:
    branches:
     - main

jobs:
  test:
    name: run qmate sample tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install qmate
        run: npm install qmate@latest -g
      - name: install qmate
        run: qmate update-chromedriver

      
      # runs automated web application walkthrough in Chrome    
      - name: run qmate config.js
        run: npm test
        
